[build]
  command = "yarn run build"

[build.environment]
  NODE_VERSION = "10.15.3"

[[redirects]]
  from = "/talk1"
  to = "/blog/how-being-a-developer-makes-me-a-better-designer"
  status = 301

[[redirects]]
  from = "/talk2"
  to = "/blog/the-rise-of-the-jamstack-dj-set"
  status = 301

[[redirects]]
  from: "/uber"
  to = "https://preview.pitch.com/app/presentation/link/33adc313-8a30-4d3f-a18a-7d331b5e2615/29abb619-77fe-4d43-a4d5-604ba6aaaa3f"
  status = 301